apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak-namespace.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - keycloak.yaml
  - keycloak-httpRoute.yaml

namespace: keycloak-namespace

configMapGenerator:
  - name: keycloak-realm
    files:
      - intwork-realm.json

secretGenerator:
  - name: db-secrets
    literals:
      - password=keycloak
  - name: keycloak-admin-secrets
    literals:
      - password=admin

generatorOptions:
  disableNameSuffixHash: true
