apiVersion: v1
kind: PersistentVolume
metadata:
  name: first-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/gluonstream"
    type: DirectoryOrCreate
---
