apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak/keycloak:26.5.2
        args:
        - "start"
        - "--import-realm"
        - "--http-enabled=true"
        - "--hostname-strict=false"
        - "--proxy-headers=xforwarded"
        - "--cache=local"
        - "--health-enabled=true"
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 9000
          name: management
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: admin
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-admin-secrets
              key: password
        - name: KC_HOSTNAME
          value: "auth.s4v3.local"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_PROXY
          value: edge
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://postgres-db:5430/keycloak
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
        - name: realm-config
          mountPath: /opt/keycloak/data/import/intwork-realm.json
          subPath: intwork-realm.json
          readOnly: true
      volumes:
      - name: realm-config
        configMap:
          name: keycloak-realm
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8443
    targetPort: 8443
  type: NodePort
