apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
data:
  intwork-realm.json: |
    {
      "id": "intwork",
      "realm": "intwork",
      "enabled": true,
      "sslRequired": "NONE",
      "loginWithEmailAllowed": true,
      "registrationAllowed": false,
      "accessTokenLifespan": 300,
      "roles": {
        "realm": [
          { "name": "admin", "description": "System administrator" },
          { "name": "manager", "description": "Department manager" },
          { "name": "employee", "description": "Standard employee" }
        ]
      },
      "clientScopes": [
        {
          "name": "roles",
          "protocol": "openid-connect",
          "attributes": { "include.in.token.scope": "true", "display.on.consent.screen": "true" },
          "protocolMappers": [
            {
              "name": "realm roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-realm-role-mapper",
              "config": { "multivalued": "true", "claim.name": "roles", "jsonType.label": "String", "access.token.claim": "true" }
            },
            {
              "name": "client roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-client-role-mapper",
              "config": { "multivalued": "true", "claim.name": "resource_access.${client_id}.roles", "jsonType.label": "String", "access.token.claim": "true" }
            }
          ]
        },
        {
          "name": "profile",
          "protocol": "openid-connect",
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "true",
            "gui.order": "",
            "consent.screen.text": "${profileScopeConsentText}",
            "include.in.openid.provider.metadata": "true"
          },
          "protocolMappers": [
            { "name": "full name", "protocol": "openid-connect", "protocolMapper": "oidc-full-name-mapper", "config": { "id.token.claim": "true", "access.token.claim": "true" } },
            { "name": "username", "protocol": "openid-connect", "protocolMapper": "oidc-usermodel-property-mapper", "config": { "user.attribute": "username", "claim.name": "preferred_username", "access.token.claim": "true" } },
            { "name": "given name", "protocol": "openid-connect", "protocolMapper": "oidc-usermodel-property-mapper", "config": { "user.attribute": "firstName", "claim.name": "given_name", "access.token.claim": "true" } },
            { "name": "family name", "protocol": "openid-connect", "protocolMapper": "oidc-usermodel-property-mapper", "config": { "user.attribute": "lastName", "claim.name": "family_name", "access.token.claim": "true" } }
          ]
        },
        {
          "name": "iaka",
          "protocol": "openid-connect",
          "protocolMappers": [
            { "name": "iaka", "protocol": "openid-connect", "protocolMapper": "oidc-usermodel-attribute-mapper", "config": { "user.attribute": "username", "claim.name": "iaka1", "jsonType.label": "String", "access.token.claim": "true" } }
          ],
          "attributes": {
            "include.in.token.scope": "true",
            "display.on.consent.screen": "true",
            "gui.order": "",
            "consent.screen.text": "iaka_screen_text",
            "include.in.openid.provider.metadata": "true"
          }
        }
      ],
      "clients": [
        {
          "clientId": "gateway-rest-client",
          "name": "gateway-rest-client",
          "description": "gateway-rest-client description",
          "rootUrl": "http://localhost:9090",
          "adminUrl": "http://localhost:9090",
          "baseUrl": "http://localhost:9090",
          "surrogateAuthRequired": false,
          "enabled": true,
          "alwaysDisplayInConsole": false,
          "clientAuthenticatorType": "client-secret",
          "secret": "TqOwvN7EBjXbX4ymF7v9VV3IftfbcpjM",
          "redirectUris": [
            "http://localhost:9090/*",
            "http://s4v3.local/*",
            "https://s4v3.local/*",
            "http://s4v3.net/*",
            "https://s4v3.net/*",
            "https://oauth.pstmn.io/v1/callback"
          ],
          "webOrigins": [
            "*"
          ],
          "notBefore": 0,
          "bearerOnly": false,
          "consentRequired": false,
          "standardFlowEnabled": true,
          "implicitFlowEnabled": false,
          "directAccessGrantsEnabled": true,
          "serviceAccountsEnabled": true,
          "publicClient": false,
          "frontchannelLogout": true,
          "protocol": "openid-connect",
          "attributes": {
            "logout.confirmation.enabled": "false",
            "client.secret.creation.time": "1768760927",
            "oauth2.jwt.authorization.grant.enabled": "true",
            "standard.token.exchange.enabled": "false",
            "frontchannel.logout.session.required": "true",
            "post.logout.redirect.uris": "http://localhost:9090/*",
            "oauth2.device.authorization.grant.enabled": "false",
            "backchannel.logout.revoke.offline.tokens": "false",
            "realm_client": "true",
            "oidc.ciba.grant.enabled": "false",
            "backchannel.logout.session.required": "true",
            "display.on.consent.screen": "true",
            "dpop.bound.access.tokens": "false"
          },
          "authenticationFlowBindingOverrides": {},
          "fullScopeAllowed": true,
          "nodeReRegistrationTimeout": -1,
          "defaultClientScopes": [
            "openid",
            "profile",
            "default-roles-intwork"
          ],
          "optionalClientScopes": [
            "uma_authorization",
            "roles",
            "iaka"
          ],
          "access": {
            "view": true,
            "configure": true,
            "manage": true
          }
        }
      ],
      "users": [
        {
          "username": "davide",
          "enabled": true,
          "email": "davide@adiwave.io",
          "firstName": "Davide",
          "lastName": "Surname",
          "emailVerified": true,
          "credentials": [{ "type": "password", "value": "a", "temporary": false }],
          "realmRoles": ["admin"],
          "clientRoles": {
            "account": ["view-profile", "manage-account"],
            "realm-management": ["view-users", "query-users"]
          }
        },
        {
          "username": "adrian",
          "enabled": true,
          "email": "adrian@adiwave.io",
          "firstName": "Adrian",
          "lastName": "Vrabie",
          "emailVerified": true,
          "credentials": [{ "type": "password", "value": "a", "temporary": false }],
          "clientRoles": {
            "account": ["view-profile", "manage-account"],
            "realm-management": ["view-users", "query-users"]
          }
        }
      ]
    }
