apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  KC_HOSTNAME: "auth.s4v3.local"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_PROXY: "edge"
  KC_DB: "postgres"
  KC_DB_URL: "jdbc:postgresql://postgres-db:5430/keycloak"
  KC_DB_USERNAME: "keycloak"
