apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: nfs-pv-1
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: nfs-pv-2
  resources:
    requests:
      storage: 1Gi
