# This PV is for the postgres-pvc
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
spec:
  capacity:
    storage: "5Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  # Retain policy means the volume is not automatically deleted when the PVC is deleted.
  # If you delete the PVC and recreate it, this PV will be in a "Released" state.
  # You must manually edit the PV (kubectl edit pv nfs-pv-1), remove the "claimRef" section,
  # and then the new PVC can bind to it.
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage_k8s/postgres
    server: 192.168.188.16
---
# This PV is for the keycloak-pvc
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
spec:
  capacity:
    storage: "5Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  # Retain policy means the volume is not automatically deleted when the PVC is deleted.
  # If you delete the PVC and recreate it, this PV will be in a "Released" state.
  # You must manually edit the PV (kubectl edit pv nfs-pv-2), remove the "claimRef" section,
  # and then the new PVC can bind to it.
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /mnt/storage_k8s/keycloak
    server: 192.168.188.16
